# Generated by Django 5.2.3 on 2025-06-30 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'store_genre',
            },
        ),
        migrations.CreateModel(
            name='DetailedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('author', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Image')),
                ('url', models.URLField(blank=True, help_text='Optional link to read the book online', max_length=500, verbose_name='External reading URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('publication_year', models.DateTimeField(auto_now_add=True, verbose_name='Publication year')),
                ('number_of_pages', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Books', to='lib.genre', verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'store_books',
                'ordering': ['name'],
            },
        ),
    ]
