# Generated by Django 5.2.3 on 2025-06-23 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_basketitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='added_at',
        ),
        migrations.AlterField(
            model_name='basket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketitems', to='store.basket'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.detailedbook'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
