# Generated by Django 5.2.3 on 2025-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_basket_created_at_remove_basketitem_added_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='detailedbook',
            name='available',
        ),
        migrations.RemoveField(
            model_name='detailedbook',
            name='price',
        ),
        migrations.AddField(
            model_name='detailedbook',
            name='url',
            field=models.URLField(blank=True, help_text='Optional link to read the book online', max_length=500, verbose_name='External reading URL'),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
